#!/bin/sh

#
# MOLPATH is needed if you want to build openbios-mol.elf
#
MOLPATH=$HOME/mol-0.9.71

if [ x"$1" = x -o "$1" = "-help" ]; then
  printf "Usage:\n  $0 [arch-config]...\n"
  printf "arch-config values supported for native or cross compiled builds:\n"
  printf " amd64, ppc, sparc32, sparc64, x86\n\n"
  printf "Add \"unix-\" prefix to compile openbios-unix executable (native only)\n"
  printf "Add \"builtin-\" prefix to compile openbios-builtin executables\n\n"
  printf "Without prefixes, builtin and unix targets are selected\n\n"
  printf "Special targets: mol-ppc briq-ppc pearpc-ppc qemu-ppc qemu-ppc64 xbox-x86\n\n"
  printf "Example: $0 builtin-sparc32 unix-amd64 builtin-amd64\n"
  exit 0
fi

is_bigendian()
{
    cpu=$1

    if test "$cpu" = "powerpc" -o "$cpu" = "ppc" \
        -o "$cpu" = "powerpc64" -o "$cpu" = "ppc64" \
        -o "$cpu" = "mips" -o "$cpu" = "s390" \
        -o "$cpu" = "sparc32" -o "$cpu" = "sparc64" \
        -o "$cpu" = "m68k" -o "$cpu" = "armv4b"; then
        echo yes
    else
        echo no
    fi
}

longbits()
{
    cpu=$1
    if test "$cpu" = "sparc64" -o "$cpu" = "ia64" \
        -o "$cpu" = "amd64" -o "$cpu" = "x86_64" \
        -o "$cpu" = "powerpc64" -o "$cpu" = "ppc64" \
        -o "$cpu" = "ppc64le" -o "$cpu" = "alpha" \
        -o "$cpu" = "aarch64" -o "$cpu" = "riscv64" ; then
        echo 64
    else
        echo 32
    fi
}

basearch()
{
    arch=$1
    case $arch in
    powerpc|ppc64|powerpc64)
        echo ppc
        ;;
    *)
        echo $arch
        ;;
    esac
}

crosscflags()
{
    host=$1
    target=$2

    hostbigendian=$(is_bigendian $host)
    hostlongbits=$(longbits $host)

    targetbigendian=$(is_bigendian $target)
    targetlongbits=$(longbits $target)

    if test "$targetbigendian" = "$hostbigendian"; then
        cflags="-USWAP_ENDIANNESS"
    else
        cflags="-DSWAP_ENDIANNESS"
    fi

    if test "$targetlongbits" = "$hostlongbits"; then
        cflags="$cflags -DNATIVE_BITWIDTH_EQUALS_HOST_BITWIDTH"
    elif test "$targetlongbits" -lt "$hostlongbits"; then
        cflags="$cflags -DNATIVE_BITWIDTH_SMALLER_THAN_HOST_BITWIDTH"
    else
        cflags="$cflags -DNATIVE_BITWIDTH_LARGER_THAN_HOST_BITWIDTH"
    fi

    if test "$target" = "sparc64" -o "$target" = "ia64" \
         -o "$target" = "amd64" -o "$target" = "x86_64" \
         -o "$target" = "alpha"; then
        if test "$host" = "x86"; then
            cflags="$cflags -DNEED_FAKE_INT128_T"
        elif test "$host" = "arm"; then
            cflags="$cflags -DNEED_FAKE_INT128_T"
        elif test "$host" = "ppc" -a `uname -s` = "Darwin"; then
            cflags="$cflags -DNEED_FAKE_INT128_T"
        fi
    fi

    CROSSCFLAGS=$cflags
}

archname()
{
    HOSTARCH=`uname -m | sed -e s/i.86/x86/ -e s/i86pc/x86/ \
	-e s/sun4u/sparc64/ -e s/sparc$/sparc32/ \
	-e s/arm64/aarch64/ -e s/arm.*/arm/ -e s/sa110/arm/ \
	-e s/x86_64/amd64/ \
	-e "s/Power Macintosh/ppc/"`
}

select_prefix()
{
    BASEARCH=$(basearch $ARCH)
    for target_arch ; do
        # OpenBIOS is freestanding firmware. Prefer bare-metal ELF/EABI
        # toolchains so Linux ABI defaults (PIE, TLS, small data, libc-facing
        # conventions) cannot leak into a ROM that QEMU loads directly.
        # Linux cross-compilers remain a compatibility fallback.
        TARGETS="${target_arch}-elf- ${target_arch}-eabi- ${target_arch}-unknown-elf- ${target_arch}-unknown-linux-gnu- ${target_arch}-linux-gnu- ${target_arch}-linux-"

        if [ x"$CROSS_COMPILE" != "x" ]; then
            TARGETS=$CROSS_COMPILE
        fi

        for TARGET in $TARGETS
        do
            if type ${TARGET}gcc > /dev/null 2>&1
            then
                return
            fi
        done
        if [ "$BASEARCH" = "$(basearch $HOSTARCH)" ]; then
            TARGET=""
            return
        fi
    done
    echo "ERROR: no $* cross-compiler found !" 1>&2
    exit 1
}

config_set_boolean()
{
    option=`echo $1 | tr a-z A-Z`
    echo "<option name=\"$option\" type=\"boolean\" value=\"true\" />"
}

exists()
{
    type "$1" >/dev/null 2>&1
}


SRCDIR=`dirname "$0"`/../..
BUILDDIR=`pwd`

# make source path absolute
SRCDIR=`cd "$SRCDIR"; pwd`

if test "x$HOSTARCH" = "x"; then
    archname
fi

VERSION=`head $SRCDIR/VERSION`

echo "Configuring OpenBIOS on $HOSTARCH for $*"

if exists toke; then
    :
else
    echo "Unable to locate toke executable from the fcode-utils package - aborting"
    exit 1
fi

target_list=""
for target in $*; do
    case $target in
        unix-*|builtin-*|plain-*|mol-ppc|briq-ppc|pearpc-ppc|qemu-ppc|qemu-ppc64|xbox-x86)
        target_list="$target_list $target"
        ;;
        cross-*)
        echo "\"cross-\" prefix is no longer needed"
        target=`echo $target | sed s/cross-//g`
        target_list="$target_list builtin-$target"
        ;;
        *)
        #default: build builtin and if possible, unix target
        target_list="$target_list builtin-$target unix-$target"
        ;;
    esac
done

arch_list=""
for target in $target_list; do
    arch=`echo $target | sed s/.*-//g`
    if ! test -f $SRCDIR/config/examples/${arch}_config.xml; then
        echo "Cannot find $SRCDIR/config/examples/${arch}_config.xml" >&2
        exit 1
    fi
    if ! echo $arch_list | grep -q "$arch"; then
        arch_list="$arch_list $arch"
    fi
done

for ARCH in $arch_list; do
    unix="no"
    builtin="no"
    plain="no"
    mol="no"
    briq="no"
    pearpc="no"
    qemu="no"
    xbox="no"
    cross="no"

    for target in $target_list; do
        case $target in
            *-$ARCH)
            :
            ;;
            *)
            continue
            ;;
        esac
        case $target in
            mol-ppc)
            mol="yes"
            ;;
            briq-ppc)
            briq="yes"
            ;;
            pearpc-ppc)
            pearpc="yes"
            ;;
            builtin-ppc|qemu-ppc|builtin-ppc64|qemu-ppc64)
            qemu="yes"
            ;;
            xbox-x86)
            xbox="yes"
            ;;
            builtin-sparc32)
            builtin="yes"
            qemu="yes"
            ;;
            builtin-sparc64)
            builtin="yes"
            qemu="yes"
            ;;
            builtin-*)
            builtin="yes"
            ;;
            plain-*)
            plain="yes"
            ;;
            unix-*)
            unix="yes"
            ;;
        esac
    done

    select_prefix $ARCH $(basearch $ARCH)
    crosscflags $HOSTARCH $ARCH

    mkdir -p $BUILDDIR/$ARCH
    cd $BUILDDIR/$ARCH
    cat > config.mak <<EOF
ARCH := $ARCH
TARGET := $TARGET
HOSTARCH := $HOSTARCH
CROSSCFLAGS := $CROSSCFLAGS
SRCDIR := $SRCDIR
BUILDDIR := $BUILDDIR
EOF

    cat $SRCDIR/config/examples/${ARCH}_config.xml |
    while read line; do
        echo "$line"
        case "$line" in
            *CONFIG_DEBUG*)
            if test "$DEBUG" = "yes"; then
                config_set_boolean CONFIG_DEBUG
            fi
            ;;
        esac
    done > config.xml

    test "$unix" = "yes" && config_set_boolean CONFIG_UNIX >> config.xml
    test "$builtin" = "yes" && config_set_boolean CONFIG_BUILTIN >> config.xml
    test "$plain" = "yes" && config_set_boolean CONFIG_PLAIN >> config.xml
    test "$mol" = "yes" && config_set_boolean CONFIG_MOL >> config.xml
    test "$briq" = "yes" && config_set_boolean CONFIG_BRIQ >> config.xml
    test "$pearpc" = "yes" && config_set_boolean CONFIG_PEARPC >> config.xml
    test "$qemu" = "yes" && config_set_boolean CONFIG_QEMU >> config.xml
    test "$xbox" = "yes" && config_set_boolean CONFIG_XBOX >> config.xml

    $SRCDIR/config/xml2dict $SRCDIR/config/config.xml config.xml > config.mak.tmp
    cat config.mak.tmp >> config.mak
    rm -f config.mak.tmp

    ln -sf $SRCDIR/Makefile.target Makefile
    cd $BUILDDIR
done
